[package]
name = "sentinel-api"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
dotenvy = "0.15"
tokio = { version = "1", features = ["full"] }
serde = "1.0.192"
axum = "0.7"

prisma = { path = "../../crates/prisma" }
